[project]
name = "trying-pyhon-yt-downloading"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mutagen>=1.47.0",
    "yt-dlp>=2025.3.31",
    "ytmusicapi>=1.10.3",
]
